class SuraModel{
 final String suraNameEn;
  final String suraNameAr;
  final String suraVerses;
  final String index;


  const SuraModel({
    required this.suraNameEn,
    required this.suraNameAr,
    required this.index,
    required this.suraVerses
});
 static const List<SuraModel> suras = [
   SuraModel(suraNameEn: "Al-Fatiha", suraNameAr: "الفاتحة", index: "1", suraVerses: "7"),
   SuraModel(suraNameEn: "Al-Baqarah", suraNameAr: "البقرة", index: "2", suraVerses: "286"),
   SuraModel(suraNameEn: "Aal-E-Imran", suraNameAr: "آل عمران", index: "3", suraVerses: "200"),
   SuraModel(suraNameEn: "An-Nisa", suraNameAr: "النساء", index: "4", suraVerses: "176"),
   SuraModel(suraNameEn: "Al-Maidah", suraNameAr: "المائدة", index: "5", suraVerses: "120"),
   SuraModel(suraNameEn: "Al-An'am", suraNameAr: "الأنعام", index: "6", suraVerses: "165"),
   SuraModel(suraNameEn: "Al-A'raf", suraNameAr: "الأعراف", index: "7", suraVerses: "206"),
   SuraModel(suraNameEn: "Al-Anfal", suraNameAr: "الأنفال", index: "8", suraVerses: "75"),
   SuraModel(suraNameEn: "At-Tawbah", suraNameAr: "التوبة", index: "9", suraVerses: "129"),
   SuraModel(suraNameEn: "Yunus", suraNameAr: "يونس", index: "10", suraVerses: "109"),
   SuraModel(suraNameEn: "Hud", suraNameAr: "هود", index: "11", suraVerses: "123"),
   SuraModel(suraNameEn: "Yusuf", suraNameAr: "يوسف", index: "12", suraVerses: "111"),
   SuraModel(suraNameEn: "Ar-Ra'd", suraNameAr: "الرعد", index: "13", suraVerses: "43"),
   SuraModel(suraNameEn: "Ibrahim", suraNameAr: "إبراهيم", index: "14", suraVerses: "52"),
   SuraModel(suraNameEn: "Al-Hijr", suraNameAr: "الحجر", index: "15", suraVerses: "99"),
   SuraModel(suraNameEn: "An-Nahl", suraNameAr: "النحل", index: "16", suraVerses: "128"),
   SuraModel(suraNameEn: "Al-Isra", suraNameAr: "الإسراء", index: "17", suraVerses: "111"),
   SuraModel(suraNameEn: "Al-Kahf", suraNameAr: "الكهف", index: "18", suraVerses: "110"),
   SuraModel(suraNameEn: "Maryam", suraNameAr: "مريم", index: "19", suraVerses: "98"),
   SuraModel(suraNameEn: "Ta-Ha", suraNameAr: "طه", index: "20", suraVerses: "135"),
   SuraModel(suraNameEn: "Al-Anbiya", suraNameAr: "الأنبياء", index: "21", suraVerses: "112"),
   SuraModel(suraNameEn: "Al-Hajj", suraNameAr: "الحج", index: "22", suraVerses: "78"),
   SuraModel(suraNameEn: "Al-Mu'minun", suraNameAr: "المؤمنون", index: "23", suraVerses: "118"),
   SuraModel(suraNameEn: "An-Nur", suraNameAr: "النور", index: "24", suraVerses: "64"),
   SuraModel(suraNameEn: "Al-Furqan", suraNameAr: "الفرقان", index: "25", suraVerses: "77"),
   SuraModel(suraNameEn: "Ash-Shu'ara", suraNameAr: "الشعراء", index: "26", suraVerses: "227"),
   SuraModel(suraNameEn: "An-Naml", suraNameAr: "النمل", index: "27", suraVerses: "93"),
   SuraModel(suraNameEn: "Al-Qasas", suraNameAr: "القصص", index: "28", suraVerses: "88"),
   SuraModel(suraNameEn: "Al-Ankabut", suraNameAr: "العنكبوت", index: "29", suraVerses: "69"),
   SuraModel(suraNameEn: "Ar-Rum", suraNameAr: "الروم", index: "30", suraVerses: "60"),
   SuraModel(suraNameEn: "Luqman", suraNameAr: "لقمان", index: "31", suraVerses: "34"),
   SuraModel(suraNameEn: "As-Sajda", suraNameAr: "السجدة", index: "32", suraVerses: "30"),
   SuraModel(suraNameEn: "Al-Ahzab", suraNameAr: "الأحزاب", index: "33", suraVerses: "73"),
   SuraModel(suraNameEn: "Saba", suraNameAr: "سبإ", index: "34", suraVerses: "54"),
   SuraModel(suraNameEn: "Fatir", suraNameAr: "فاطر", index: "35", suraVerses: "45"),
   SuraModel(suraNameEn: "Ya-Sin", suraNameAr: "يس", index: "36", suraVerses: "83"),
   SuraModel(suraNameEn: "As-Saffat", suraNameAr: "الصافات", index: "37", suraVerses: "182"),
   SuraModel(suraNameEn: "Sad", suraNameAr: "ص", index: "38", suraVerses: "88"),
   SuraModel(suraNameEn: "Az-Zumar", suraNameAr: "الزمر", index: "39", suraVerses: "75"),
   SuraModel(suraNameEn: "Ghafir", suraNameAr: "غافر", index: "40", suraVerses: "85"),
   SuraModel(suraNameEn: "Fussilat", suraNameAr: "فصلت", index: "41", suraVerses: "54"),
   SuraModel(suraNameEn: "Ash-Shura", suraNameAr: "الشورى", index: "42", suraVerses: "53"),
   SuraModel(suraNameEn: "Az-Zukhruf", suraNameAr: "الزخرف", index: "43", suraVerses: "89"),
   SuraModel(suraNameEn: "Ad-Dukhan", suraNameAr: "الدخان", index: "44", suraVerses: "59"),
   SuraModel(suraNameEn: "Al-Jathiya", suraNameAr: "الجاثية", index: "45", suraVerses: "37"),
   SuraModel(suraNameEn: "Al-Ahqaf", suraNameAr: "الأحقاف", index: "46", suraVerses: "35"),
   SuraModel(suraNameEn: "Muhammad", suraNameAr: "محمد", index: "47", suraVerses: "38"),
   SuraModel(suraNameEn: "Al-Fath", suraNameAr: "الفتح", index: "48", suraVerses: "29"),
   SuraModel(suraNameEn: "Al-Hujurat", suraNameAr: "الحجرات", index: "49", suraVerses: "18"),
   SuraModel(suraNameEn: "Qaf", suraNameAr: "ق", index: "50", suraVerses: "45"),
   SuraModel(suraNameEn: "Adh-Dhariyat", suraNameAr: "الذاريات", index: "51", suraVerses: "60"),
   SuraModel(suraNameEn: "At-Tur", suraNameAr: "الطور", index: "52", suraVerses: "49"),
   SuraModel(suraNameEn: "An-Najm", suraNameAr: "النجم", index: "53", suraVerses: "62"),
   SuraModel(suraNameEn: "Al-Qamar", suraNameAr: "القمر", index: "54", suraVerses: "55"),
   SuraModel(suraNameEn: "Ar-Rahman", suraNameAr: "الرحمن", index: "55", suraVerses: "78"),
   SuraModel(suraNameEn: "Al-Waqia", suraNameAr: "الواقعة", index: "56", suraVerses: "96"),
   SuraModel(suraNameEn: "Al-Hadid", suraNameAr: "الحديد", index: "57", suraVerses: "29"),
   SuraModel(suraNameEn: "Al-Mujadila", suraNameAr: "المجادلة", index: "58", suraVerses: "22"),
   SuraModel(suraNameEn: "Al-Hashr", suraNameAr: "الحشر", index: "59", suraVerses: "24"),
   SuraModel(suraNameEn: "Al-Mumtahina", suraNameAr: "الممتحنة", index: "60", suraVerses: "13"),
   SuraModel(suraNameEn: "As-Saff", suraNameAr: "الصف", index: "61", suraVerses: "14"),
   SuraModel(suraNameEn: "Al-Jumua", suraNameAr: "الجمعة", index: "62", suraVerses: "11"),
   SuraModel(suraNameEn: "Al-Munafiqun", suraNameAr: "المنافقون", index: "63", suraVerses: "11"),
   SuraModel(suraNameEn: "At-Taghabun", suraNameAr: "التغابن", index: "64", suraVerses: "18"),
   SuraModel(suraNameEn: "At-Talaq", suraNameAr: "الطلاق", index: "65", suraVerses: "12"),
   SuraModel(suraNameEn: "At-Tahrim", suraNameAr: "التحريم", index: "66", suraVerses: "12"),
   SuraModel(suraNameEn: "Al-Mulk", suraNameAr: "الملك", index: "67", suraVerses: "30"),
   SuraModel(suraNameEn: "Al-Qalam", suraNameAr: "القلم", index: "68", suraVerses: "52"),
   SuraModel(suraNameEn: "Al-Haaqqa", suraNameAr: "الحاقة", index: "69", suraVerses: "52"),
   SuraModel(suraNameEn: "Al-Maarij", suraNameAr: "المعارج", index: "70", suraVerses: "44"),
   SuraModel(suraNameEn: "Nuh", suraNameAr: "نوح", index: "71", suraVerses: "28"),
   SuraModel(suraNameEn: "Al-Jinn", suraNameAr: "الجن", index: "72", suraVerses: "28"),
   SuraModel(suraNameEn: "Al-Muzzammil", suraNameAr: "المزمل", index: "73", suraVerses: "20"),
   SuraModel(suraNameEn: "Al-Muddathir", suraNameAr: "المدثر", index: "74", suraVerses: "56"),
   SuraModel(suraNameEn: "Al-Qiyama", suraNameAr: "القيامة", index: "75", suraVerses: "40"),
   SuraModel(suraNameEn: "Al-Insan", suraNameAr: "الإنسان", index: "76", suraVerses: "31"),
   SuraModel(suraNameEn: "Al-Mursalat", suraNameAr: "المرسلات", index: "77", suraVerses: "50"),
   SuraModel(suraNameEn: "An-Naba", suraNameAr: "النبأ", index: "78", suraVerses: "40"),
   SuraModel(suraNameEn: "An-Nazi'at", suraNameAr: "النازعات", index: "79", suraVerses: "46"),
   SuraModel(suraNameEn: "Abasa", suraNameAr: "عبس", index: "80", suraVerses: "42"),
   SuraModel(suraNameEn: "At-Takwir", suraNameAr: "التكوير", index: "81", suraVerses: "29"),
   SuraModel(suraNameEn: "Al-Infitar", suraNameAr: "الانفطار", index: "82", suraVerses: "19"),
   SuraModel(suraNameEn: "Al-Mutaffifin", suraNameAr: "المطففين", index: "83", suraVerses: "36"),
   SuraModel(suraNameEn: "Al-Inshiqaq", suraNameAr: "الانشقاق", index: "84", suraVerses: "25"),
   SuraModel(suraNameEn: "Al-Buruj", suraNameAr: "البروج", index: "85", suraVerses: "22"),
   SuraModel(suraNameEn: "At-Tariq", suraNameAr: "الطارق", index: "86", suraVerses: "17"),
   SuraModel(suraNameEn: "Al-Ala", suraNameAr: "الأعلى", index: "87", suraVerses: "19"),
   SuraModel(suraNameEn: "Al-Ghashiya", suraNameAr: "الغاشية", index: "88", suraVerses: "26"),
   SuraModel(suraNameEn: "Al-Fajr", suraNameAr: "الفجر", index: "89", suraVerses: "30"),
   SuraModel(suraNameEn: "Al-Balad", suraNameAr: "البلد", index: "90", suraVerses: "20"),
   SuraModel(suraNameEn: "Ash-Shams", suraNameAr: "الشمس", index: "91", suraVerses: "15"),
   SuraModel(suraNameEn: "Al-Lail", suraNameAr: "الليل", index: "92", suraVerses: "21"),
   SuraModel(suraNameEn: "Ad-Duhaa", suraNameAr: "الضحى", index: "93", suraVerses: "11"),
   SuraModel(suraNameEn: "Ash-Sharh", suraNameAr: "الشرح", index: "94", suraVerses: "8"),
   SuraModel(suraNameEn: "At-Tin", suraNameAr: "التين", index: "95", suraVerses: "8"),
   SuraModel(suraNameEn: "Al-Alaq", suraNameAr: "العلق", index: "96", suraVerses: "19"),
   SuraModel(suraNameEn: "Al-Qadr", suraNameAr: "القدر", index: "97", suraVerses: "5"),
   SuraModel(suraNameEn: "Al-Bayyina", suraNameAr: "البينة", index: "98", suraVerses: "8"),
   SuraModel(suraNameEn: "Az-Zalzala", suraNameAr: "الزلزلة", index: "99", suraVerses: "8"),
   SuraModel(suraNameEn: "Al-Adiyat", suraNameAr: "العاديات", index: "100", suraVerses: "11"),
   SuraModel(suraNameEn: "Al-Qaria", suraNameAr: "القارعة", index: "101", suraVerses: "11"),
   SuraModel(suraNameEn: "At-Takathur", suraNameAr: "التكاثر", index: "102", suraVerses: "8"),
   SuraModel(suraNameEn: "Al-Asr", suraNameAr: "العصر", index: "103", suraVerses: "3"),
   SuraModel(suraNameEn: "Al-Humaza", suraNameAr: "الهمزة", index: "104", suraVerses: "9"),
   SuraModel(suraNameEn: "Al-Fil", suraNameAr: "الفيل", index: "105", suraVerses: "5"),
   SuraModel(suraNameEn: "Quraish", suraNameAr: "قريش", index: "106", suraVerses: "4"),
   SuraModel(suraNameEn: "Al-Ma'un", suraNameAr: "الماعون", index: "107", suraVerses: "7"),
   SuraModel(suraNameEn: "Al-Kawthar", suraNameAr: "الكوثر", index: "108", suraVerses: "3"),
   SuraModel(suraNameEn: "Al-Kafiroon", suraNameAr: "الكافرون", index: "109", suraVerses: "6"),
   SuraModel(suraNameEn: "An-Nasr", suraNameAr: "النصر", index: "110", suraVerses: "3"),
   SuraModel(suraNameEn: "Al-Masad", suraNameAr: "المسد", index: "111", suraVerses: "5"),
   SuraModel(suraNameEn: "Al-Ikhlas", suraNameAr: "الإخلاص", index: "112", suraVerses: "4"),
   SuraModel(suraNameEn: "Al-Falaq", suraNameAr: "الفلق", index: "113", suraVerses: "5"),
   SuraModel(suraNameEn: "An-Nas", suraNameAr: "الناس", index: "114", suraVerses: "6"),
 ];
}